batch_size: 128
class_num: 100
with_test: True
epoch: 20
log_step: 10
save_per_epoch: 2
save_metric: 'raw_acc'
best_model_path: './results/checkpoints/best_checkpoint.pth'
pred_dir: './results/pred'
loss_weight:
  - 1.0
  - 1.0

optimizer_cfg:
  lr: 1.0e-3
  weight_decay: 5.0e-4

scheduler_cfg: 
  gamma: 0.1
  milestones: [2, 5, 10, 15]