batch_size: 64
class_num: 10
with_test: True
epoch: 20
log_step: 10
log_image_step: 200
save_per_epoch: 2
save_metric: 'AuC'
best_model_path: './results/checkpoints/best_checkpoint.pth'
pred_dir: './results/pred'
loss_weight:
  - 1.0
  - 0.5

optimizer_cfg:
  lr: 1.0e-4
  weight_decay: 5.0e-4

scheduler_cfg: 
  gamma: 0.4
  milestones: [5, 10, 15, 18]