batch_size: 32
class_num: 10
with_test: True
epoch: 24
log_step: 10
save_per_epoch: 2
save_metric: 'raw_acc'
best_model_path: './results/checkpoints/best_checkpoint.pth'
pred_dir: './results/pred'
loss_weight:
  - 1.0
  - 0.005

optimizer_cfg:
  lr: 1.0e-4
  weight_decay: 5.0e-4

scheduler_cfg: 
  gamma: 0.3
  milestones: [6, 12, 18, 22]